# Generated by Django 4.2.18 on 2026-02-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0008_customermodel_terms_accepted_and_more"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("amount", "Fixed amount")],
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_redemptions_total",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_redemptions_per_customer",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_gross_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_discount_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.bookingmodel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.customermodel",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="promotions.promocode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["promo"], name="promotions__promo_i_e2e2e2_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="promotions__custome_a48388_idx"
                    ),
                ],
            },
        ),
    ]
