# Generated by Django 4.2.18 on 2026-01-30 11:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_day_rental",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("350.00"), max_digits=10
                    ),
                ),
                (
                    "gross_dealer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("250.00"), max_digits=10
                    ),
                ),
                (
                    "gross_service",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("250.00"), max_digits=10
                    ),
                ),
                (
                    "gross_drinks_flatrate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("150.00"), max_digits=10
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.19"), max_digits=4
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500.00"), max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Configuration",
                "verbose_name_plural": "Pricing Configuration",
            },
        ),
    ]
