# Generated by Django 4.2.18 on 2025-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='otp_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='Email', max_length=10),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
    ]
