# Generated by Django 4.2.18 on 2025-02-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_email_id_customermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='destination',
            field=models.CharField(default='', max_length=255),
        ),
    ]
