# Generated by Django 4.2.18 on 2025-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_otpmodel_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='phone_verified',
            new_name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='destination',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=5),
        ),
    ]
