# Generated by Django 4.2.18 on 2025-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_email_customermodel_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
