# Generated by Django 4.2.18 on 2025-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customermodel_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="braintree_customer_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the Customer in Braintree's vault",
                max_length=50,
                null=True,
            ),
        ),
    ]
