# Generated by Django 4.2.18 on 2025-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customermodel_braintree_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
