# Generated by Django 4.2.18 on 2025-11-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='terms_version',
            field=models.CharField(blank=True, default='v1', max_length=20),
        ),
    ]
