# Generated by Django 4.2.18 on 2026-01-30 11:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0008_customermodel_terms_accepted_and_more"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnavailableTimeSlotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="BookingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("total_people", models.PositiveIntegerField()),
                ("hours_booked", models.PositiveIntegerField()),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_cash", models.BooleanField(default=False)),
                ("cash_paid", models.BooleanField(default=False)),
                (
                    "cash_rounding_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("has_dealer", models.BooleanField(default=False)),
                ("has_service_personal", models.BooleanField(default=False)),
                ("has_drinks_flatrate", models.BooleanField(default=False)),
                (
                    "deposit_payment_intent_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("deposit_refunded", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="customers.customermodel",
                    ),
                ),
                (
                    "drinks",
                    models.ManyToManyField(
                        blank=True, related_name="bookings", to="menu.drinkmodel"
                    ),
                ),
            ],
        ),
    ]
