# Generated by Django 4.2.18 on 2026-02-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmodel",
            name="discount_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bookingmodel",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotions.promocode",
            ),
        ),
        migrations.AddField(
            model_name="bookingmodel",
            name="total_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
