# Generated by Django 4.2.18 on 2026-02-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingmodel_discount_gross_bookingmodel_promo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_cutoff_days', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
