# Generated by Django 4.2.18 on 2025-09-15 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_bookingmodel_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmodel",
            name="booking_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
