# Generated by Django 4.2.18 on 2025-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_bookingmodel_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingmodel",
            name="booking_date",
            field=models.DateField(),
        ),
    ]
