# Generated by Django 4.2.18 on 2025-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingmodel_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
