# Generated by Django 4.2.18 on 2026-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingmodel_is_active'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bookings_bookingmodel
                        ADD COLUMN IF NOT EXISTS deposit_payment_intent_id varchar(255);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="bookingmodel",
                    name="deposit_payment_intent_id",
                    field=models.CharField(max_length=255, null=True, blank=True),
                ),
            ],
        ),
    ]
