# Generated by Django 4.2.18 on 2026-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='deposit_payment_intent_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
