# Generated by Django 4.2.18 on 2026-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('bookings', '0006_bookingmodel_deposit_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='drinks',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='menu.drinkmodel'),
        ),
    ]
