# Generated by Django 4.2.18 on 2026-01-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookingmodel_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='is_paid_online',
            field=models.BooleanField(default=False),
        ),
    ]
