# Generated by Django 4.2.18 on 2026-01-26 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingmodel_is_paid_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='is_paid_online',
            new_name='is_cash',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='cash_rounding_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
