# Generated by Django 4.2.18 on 2026-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_is_paid_online_bookingmodel_is_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='cash_paid',
            field=models.BooleanField(default=False),
        ),
    ]
