# Generated by Django 4.2.18 on 2026-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_bookingmodel_cash_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='has_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='has_drinks_flatrate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='has_service_personal',
            field=models.BooleanField(default=False),
        ),
    ]
